# Generated by Django 5.2.17 on 2026-09-06 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(default='FCFA', max_length=10)),
                ('mobile_money_services', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data_type', models.CharField(choices=[('audio', 'Audio'), ('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=10)),
                ('target_count', models.IntegerField(default=1000)),
                ('current_count', models.IntegerField(default=0)),
                ('price_per_item', models.DecimalField(decimal_places=4, max_digits=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('instructions', models.TextField(blank=True)),
                ('sample_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.language')),
            ],
            options={
                'verbose_name_plural': 'data collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/%Y/%m/%d/')),
                ('transcription', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('review', 'Under Review')], default='pending', max_length=10)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='workers.datacollection')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.ManyToManyField(blank=True, to='workers.language'),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('level', models.IntegerField(choices=[(1, 'Data Worker'), (2, 'Verified Annotator'), (3, 'Language Specialist'), (4, 'AI Evaluator'), (5, 'Domain Expert')], default=1)),
                ('quality_score', models.FloatField(default=0.0)),
                ('total_tasks', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.country')),
                ('languages', models.ManyToManyField(blank=True, to='workers.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quality_score'],
            },
        ),
        migrations.CreateModel(
            name='QualityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.datasubmission')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_logs', to='workers.worker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datasubmission',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='workers.worker'),
        ),
        migrations.CreateModel(
            name='WorkerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Data Worker'), (2, 'Verified Annotator'), (3, 'Language Specialist'), (4, 'AI Evaluator'), (5, 'Domain Expert')])),
                ('tasks_required', models.IntegerField(default=100)),
                ('accuracy_required', models.FloatField(default=80.0)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('tasks_at_unlock', models.IntegerField(default=0)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level_info', to='workers.worker')),
            ],
        ),
    ]
