# Generated by Django 5.2.17 on 2026-09-07 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('image_bbox', 'Image Bounding Box'), ('image_segmentation', 'Image Segmentation'), ('image_classification', 'Image Classification'), ('text_classification', 'Text Classification'), ('text_ner', 'Named Entity Recognition'), ('text_sentiment', 'Sentiment Analysis'), ('text_translation', 'Translation'), ('audio_transcription', 'Audio Transcription'), ('audio_classification', 'Audio Classification'), ('conversation_rating', 'Conversation Rating')], max_length=25)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Expert')], default=2)),
                ('reward', models.DecimalField(decimal_places=4, default=0.1, max_digits=8)),
                ('input_data', models.JSONField(default=dict, help_text='Data to annotate')),
                ('expected_output', models.JSONField(default=dict, help_text='Expected annotation format')),
                ('instructions', models.TextField(blank=True)),
                ('max_annotations', models.IntegerField(default=3, help_text='Max workers per task')),
                ('current_annotations', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('review', 'Under Review')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_annotation_tasks', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.language')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_data', models.JSONField(default=dict, help_text='The annotation output')),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='workers.worker')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='workers.annotationtask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('payment_received', 'Payment Received'), ('payment_processing', 'Payment Processing'), ('level_up', 'Level Up'), ('evaluation_complete', 'Evaluation Complete'), ('collection_ready', 'Collection Ready'), ('system', 'System')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict, help_text='Additional data')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('crypto', 'Cryptocurrency')], default='mobile_money', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='For mobile money', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('task_type', models.CharField(blank=True, help_text='Type of task earned from', max_length=50)),
                ('task_id', models.IntegerField(blank=True, help_text='ID of completed task', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='workers.worker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RLHFTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('comparison', 'Response Comparison (A vs B)'), ('ranking', 'Rank Multiple Responses'), ('rating', 'Rate Response Quality'), ('preference', 'Preference Pair'), ('correction', 'Text Correction')], max_length=20)),
                ('prompt', models.TextField(help_text='The AI prompt/query')),
                ('responses', models.JSONField(default=list, help_text='List of AI responses to evaluate')),
                ('context', models.JSONField(default=dict, help_text='Additional context for evaluation')),
                ('reward', models.DecimalField(decimal_places=4, default=0.15, max_digits=8)),
                ('max_workers', models.IntegerField(default=5)),
                ('current_workers', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rlhftasks', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.language')),
            ],
            options={
                'verbose_name_plural': 'RLHF tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyntheticDataJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('generation_type', models.CharField(choices=[('conversation', 'Conversation Generation'), ('translation', 'Translation Pairs'), ('qa_pairs', 'Q&A Pairs'), ('text_variations', 'Text Variations'), ('entity_data', 'Named Entity Data'), ('sentiment_data', 'Sentiment Labeled Text')], max_length=25)),
                ('parameters', models.JSONField(default=dict, help_text='Generation parameters')),
                ('target_count', models.IntegerField(default=100)),
                ('current_count', models.IntegerField(default=0)),
                ('output_data', models.JSONField(default=list, help_text='Generated data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synthetic_jobs', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.language')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RLHFFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_response', models.IntegerField(help_text='Index of preferred response')),
                ('confidence', models.FloatField(default=0.8, help_text='Worker confidence 0-1')),
                ('reasoning', models.TextField(blank=True, help_text='Why this response was chosen')),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rlhf_feedbacks', to='workers.worker')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='workers.rlhftask')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('task', 'worker')},
            },
        ),
    ]
